---
- hosts: default
  vars:
    package_list:
      - java-1.8.0-openjdk-headless
      - tomcat

    hyrax_version: "1.16"

    opendap_pub_url: "https://www.opendap.org/pub"
    opendap_rpm_url: "{{ opendap_pub_url }}/binary/hyrax-{{ hyrax_version }}/centos-7.x"

    bes_version: "3.20.6"
    bes_rpm_release: "1"
    bes_rpm: "bes-{{ bes_version }}-{{ bes_rpm_release }}.static.el7.x86_64.rpm"
    bes_rpm_url: "{{ opendap_rpm_url }}/{{ bes_rpm }}"
    bes_rpm_sha256: "987d6557dc94b7839bc89f78ed739e4a8bed497e0565e70f726fb1f97863a12b"

    libdap_version: "3.20.5"
    libdap_rpm_release: "1"
    libdap_rpm: "libdap-{{ libdap_version }}-{{ libdap_rpm_release}}.el7.x86_64.rpm"
    libdap_rpm_url: "{{ opendap_rpm_url }}/{{ libdap_rpm }}"
    libdap_rpm_sha256: "0f3b19468d442d84a6810dddeed1ce5c407d7a65d2556007b5db18ed0ed91e95"

    olfs_version: "1.18.6"
    olfs_tgz: "olfs-{{ olfs_version }}-webapp.tgz"
    olfs_tgz_url: "{{ opendap_pub_url }}/olfs/{{ olfs_tgz }}"
    olfs_tgz_sha256: "b48235c4890235dba25940b1d433b6a732ab6f73fbd66b7886dc09c63b839a41"

    local: "/vagrant"
    downloads: "{{ local }}/downloads"

    tomcat_directory_list:
      - "."
      - "conf"
      - "content"
      - "content/opendap"
      - "lib"
      - "logs"
      - "temp"
      - "webapps"
      - "work"

    tomcat_conf_file_list:
      - "catalina.policy"
      - "catalina.properties"
      - "context.xml"
      - "log4j.properties"
      - "logging.properties"
      - "web.xml"

  tasks:
    - name: "Download files"
      block:
        - file:
            path: "{{ downloads }}"
            state: directory
        - loop:
            - { url: "{{ bes_rpm_url }}", sha256: "{{ bes_rpm_sha256 }}" }
            - { url: "{{ libdap_rpm_url }}", sha256: "{{ libdap_rpm_sha256 }}" }
            - { url: "{{ olfs_tgz_url }}", sha256: "{{ olfs_tgz_sha256 }}" }
          get_url:
            url: "{{ item.url }}"
            dest: "{{ downloads }}/"
            checksum: "sha256:{{ item.sha256 }}"

    - name: "Install packages and configure services"
      become: yes
      block:
        - package:
            state: installed
            name: "{{ package_list }}"
        - copy:
            src: "bes@.service"
            dest: "/etc/systemd/system/"
            owner: root
            group: root
            mode: 0644
        - loop: "{{ instances }}"
          copy:
            dest: "/etc/sysconfig/tomcat@{{ item.shortname }}"
            content: |
              JAVA_HOME="/usr/lib/jvm/jre-1.8.0"
              JAVA_OPTS="-server -Djava.awt.headless=true -Xmx1500M -Xms1500M -XX:+DisableAttachMechanism"
              CATALINA_TMPDIR=/var/lib/tomcats/{{ item.shortname }}/temp
              OLFS_CONFIG_DIR=/var/lib/tomcats/{{ item.shortname }}/content/opendap
        - loop: "{{ instances|product(tomcat_directory_list)|list }}"
          file:
            path: "/var/lib/tomcats/{{ item.0.shortname }}/{{ item.1 }}"
            state: directory
            owner: tomcat
            group: tomcat
            mode: 02775
        - loop: "{{ instances }}"
          template:
            dest: "/var/lib/tomcats/{{ item.shortname }}/conf/server.xml"
            src: "server.xml.j2"
            owner: tomcat
            group: tomcat
            mode: 0644
        - loop: "{{ instances|product(tomcat_conf_file_list)|list }}"
          copy:
            remote_src: yes
            src: "/etc/tomcat/{{ item.1 }}"
            dest: "/var/lib/tomcats/{{ item.0.shortname }}/conf/"
            owner: tomcat
            group: tomcat
            mode: 0644
        - loop: "{{ instances }}"
          service:
            name: "tomcat@{{ item.shortname }}"
            enabled: yes
            state: started
        - loop: "{{ instances }}"
          unarchive:
            remote_src: yes
            src: "{{ downloads }}/{{ olfs_tgz }}"
            dest: "/var/lib/tomcats/{{ item.shortname }}/webapps"
            creates: "/var/lib/tomcats/{{ item.shortname }}/webapps/opendap.war"
            exclude:
              - "README"
            extra_opts:
              - "--strip-components=1"
            owner: tomcat
            group: tomcat
            mode: 0644
        - name: "START"
          debug:
            msg: starting...
